### ISSUE TITLE
Smtp :: Feature request

### ISSUE THREAD

**Issue by ghost** [Aurochses/Aurochses.IdentityServer.Website#6]
Hi @rodchenkov,

Kindly add standard smtp functionality and config for sending out mail 🥇

**Comment by rodchenkov** [comment]
Hi @nicotravassos 

Thank you for your feedback.
Sending email is solved using DI so to change SendGrid to direct smtp sending you can change DI in project for IEmailService.

Please let me know if you have any questions or suggestion how to solve this in other way.
